import { RequestTripDto } from "./dto/request-trip.dto";
import { TripsService } from "./trips.service";
export declare class TripsController {
    private readonly tripsService;
    constructor(tripsService: TripsService);
    requestTrip(user: any, dto: RequestTripDto): Promise<{
        ok: boolean;
        message: string;
        trip?: undefined;
    } | {
        ok: boolean;
        trip: {
            fare: {
                createdAt: Date;
                tripId: string;
                currency: import(".prisma/client").$Enums.Currency;
                baseFare: number;
                perKmFare: number;
                perMinFare: number;
                bookingFee: number;
                discount: number;
                totalAmount: number;
                platformEarning: number;
                driverEarning: number;
                distanceKm: number | null;
                durationMin: number | null;
            };
            delivery: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                tripId: string;
                itemDescription: string;
                recipientName: string;
                recipientPhone: string;
                noteToCourier: string | null;
            };
            driver: {
                id: string;
                city: import(".prisma/client").$Enums.City;
                createdAt: Date;
                updatedAt: Date;
                userId: string;
                driverType: import(".prisma/client").$Enums.DriverType;
                kycStatus: import(".prisma/client").$Enums.KycStatus;
                availability: import(".prisma/client").$Enums.Availability;
                isBusy: boolean;
                approvedAt: Date | null;
                rejectedAt: Date | null;
                kycNote: string | null;
            };
            rider: {
                id: string;
                status: import(".prisma/client").$Enums.UserStatus;
                createdAt: Date;
                updatedAt: Date;
                phone: string;
                role: import(".prisma/client").$Enums.Role;
                fullName: string | null;
                email: string | null;
                isMerchant: boolean;
                merchantTrusted: boolean;
            };
        } & {
            id: string;
            serviceType: import(".prisma/client").$Enums.ServiceType;
            city: import(".prisma/client").$Enums.City;
            status: import(".prisma/client").$Enums.TripStatus;
            cancelledBy: import(".prisma/client").$Enums.CancelledBy | null;
            cancelReason: string | null;
            pickupAddress: string;
            pickupLat: number;
            pickupLng: number;
            dropoffAddress: string;
            dropoffLat: number;
            dropoffLng: number;
            distanceKmEst: number | null;
            durationMinEst: number | null;
            requestedAt: Date;
            matchedAt: Date | null;
            acceptedAt: Date | null;
            arrivedAt: Date | null;
            startedAt: Date | null;
            completedAt: Date | null;
            cancelledAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            paymentMode: import(".prisma/client").$Enums.PaymentMode;
            commitmentStatus: import(".prisma/client").$Enums.CommitmentStatus;
            commitmentAmount: number | null;
            commitmentWaivedAt: Date | null;
            commitmentWaivedBy: string | null;
            commitmentReason: string | null;
            riderId: string;
            driverId: string | null;
        };
        message?: undefined;
    }>;
    inbox(user: any): Promise<{
        ok: boolean;
        message: string;
        phase4Marker?: undefined;
        expiredCount?: undefined;
        count?: undefined;
        windowMinutes?: undefined;
        driver?: undefined;
        trips?: undefined;
    } | {
        ok: boolean;
        phase4Marker: string;
        expiredCount: number;
        count: number;
        windowMinutes: number;
        driver: {
            id: string;
            userId: string;
            driverType: import(".prisma/client").$Enums.DriverType;
            city: "ABUJA";
            availability: "ONLINE";
            lat: number;
            lng: number;
            lastSeenAt: Date;
        };
        trips: {
            distanceKm: number;
            delivery: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                tripId: string;
                itemDescription: string;
                recipientName: string;
                recipientPhone: string;
                noteToCourier: string | null;
            };
            rider: {
                id: string;
                status: import(".prisma/client").$Enums.UserStatus;
                createdAt: Date;
                updatedAt: Date;
                phone: string;
                role: import(".prisma/client").$Enums.Role;
                fullName: string | null;
                email: string | null;
                isMerchant: boolean;
                merchantTrusted: boolean;
            };
            id: string;
            serviceType: import(".prisma/client").$Enums.ServiceType;
            city: import(".prisma/client").$Enums.City;
            status: import(".prisma/client").$Enums.TripStatus;
            cancelledBy: import(".prisma/client").$Enums.CancelledBy | null;
            cancelReason: string | null;
            pickupAddress: string;
            pickupLat: number;
            pickupLng: number;
            dropoffAddress: string;
            dropoffLat: number;
            dropoffLng: number;
            distanceKmEst: number | null;
            durationMinEst: number | null;
            requestedAt: Date;
            matchedAt: Date | null;
            acceptedAt: Date | null;
            arrivedAt: Date | null;
            startedAt: Date | null;
            completedAt: Date | null;
            cancelledAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            paymentMode: import(".prisma/client").$Enums.PaymentMode;
            commitmentStatus: import(".prisma/client").$Enums.CommitmentStatus;
            commitmentAmount: number | null;
            commitmentWaivedAt: Date | null;
            commitmentWaivedBy: string | null;
            commitmentReason: string | null;
            riderId: string;
            driverId: string | null;
        }[];
        message?: undefined;
    }>;
}
