import { PrismaService } from "../prisma/prisma.service";
import { RequestTripDto } from "./dto/request-trip.dto";
export declare class TripsService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    private toRad;
    private haversineKm;
    findEligibleDriversForTrip(tripId: string): Promise<{
        ok: boolean;
        message: string;
        trip?: undefined;
        count?: undefined;
        drivers?: undefined;
        queriedDrivers?: undefined;
    } | {
        ok: boolean;
        trip: {
            id: string;
            serviceType: import(".prisma/client").$Enums.ServiceType;
            city: "ABUJA";
            pickupLat: number;
            pickupLng: number;
        };
        count: number;
        drivers: {
            driverId: string;
            userId: string;
            fullName: string;
            phone: string;
            driverType: import(".prisma/client").$Enums.DriverType;
            city: "ABUJA";
            kycStatus: import(".prisma/client").$Enums.KycStatus;
            availability: import(".prisma/client").$Enums.Availability;
            hasLocation: boolean;
            lat: number;
            lng: number;
            heading: number;
            accuracyM: number;
            lastSeenAt: Date;
            seenAtMs: number;
            nowMs: number;
            ageMs: number;
            isFresh: boolean;
            matchesServiceType: boolean;
            distanceKm: number;
            passesFinalFilter: boolean;
            reasons: string[];
        }[];
        queriedDrivers: {
            driverId: string;
            userId: string;
            fullName: string;
            phone: string;
            driverType: import(".prisma/client").$Enums.DriverType;
            city: "ABUJA";
            kycStatus: import(".prisma/client").$Enums.KycStatus;
            availability: import(".prisma/client").$Enums.Availability;
            hasLocation: boolean;
            lat: number;
            lng: number;
            heading: number;
            accuracyM: number;
            lastSeenAt: Date;
            seenAtMs: number;
            nowMs: number;
            ageMs: number;
            isFresh: boolean;
            matchesServiceType: boolean;
            distanceKm: number;
            passesFinalFilter: boolean;
            reasons: string[];
        }[];
        message?: undefined;
    }>;
    requestTrip(user: any, dto: RequestTripDto): Promise<{
        ok: boolean;
        message: string;
        trip?: undefined;
    } | {
        ok: boolean;
        trip: {
            fare: {
                createdAt: Date;
                tripId: string;
                currency: import(".prisma/client").$Enums.Currency;
                baseFare: number;
                perKmFare: number;
                perMinFare: number;
                bookingFee: number;
                discount: number;
                totalAmount: number;
                platformEarning: number;
                driverEarning: number;
                distanceKm: number | null;
                durationMin: number | null;
            };
            delivery: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                tripId: string;
                itemDescription: string;
                recipientName: string;
                recipientPhone: string;
                noteToCourier: string | null;
            };
            driver: {
                id: string;
                city: import(".prisma/client").$Enums.City;
                createdAt: Date;
                updatedAt: Date;
                userId: string;
                driverType: import(".prisma/client").$Enums.DriverType;
                kycStatus: import(".prisma/client").$Enums.KycStatus;
                availability: import(".prisma/client").$Enums.Availability;
                isBusy: boolean;
                approvedAt: Date | null;
                rejectedAt: Date | null;
                kycNote: string | null;
            };
            rider: {
                id: string;
                status: import(".prisma/client").$Enums.UserStatus;
                createdAt: Date;
                updatedAt: Date;
                phone: string;
                role: import(".prisma/client").$Enums.Role;
                fullName: string | null;
                email: string | null;
                isMerchant: boolean;
                merchantTrusted: boolean;
            };
        } & {
            id: string;
            serviceType: import(".prisma/client").$Enums.ServiceType;
            city: import(".prisma/client").$Enums.City;
            status: import(".prisma/client").$Enums.TripStatus;
            cancelledBy: import(".prisma/client").$Enums.CancelledBy | null;
            cancelReason: string | null;
            pickupAddress: string;
            pickupLat: number;
            pickupLng: number;
            dropoffAddress: string;
            dropoffLat: number;
            dropoffLng: number;
            distanceKmEst: number | null;
            durationMinEst: number | null;
            requestedAt: Date;
            matchedAt: Date | null;
            acceptedAt: Date | null;
            arrivedAt: Date | null;
            startedAt: Date | null;
            completedAt: Date | null;
            cancelledAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            paymentMode: import(".prisma/client").$Enums.PaymentMode;
            commitmentStatus: import(".prisma/client").$Enums.CommitmentStatus;
            commitmentAmount: number | null;
            commitmentWaivedAt: Date | null;
            commitmentWaivedBy: string | null;
            commitmentReason: string | null;
            riderId: string;
            driverId: string | null;
        };
        message?: undefined;
    }>;
    myTrips(user: any): Promise<{
        ok: boolean;
        trips: ({
            fare: {
                createdAt: Date;
                tripId: string;
                currency: import(".prisma/client").$Enums.Currency;
                baseFare: number;
                perKmFare: number;
                perMinFare: number;
                bookingFee: number;
                discount: number;
                totalAmount: number;
                platformEarning: number;
                driverEarning: number;
                distanceKm: number | null;
                durationMin: number | null;
            };
            delivery: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                tripId: string;
                itemDescription: string;
                recipientName: string;
                recipientPhone: string;
                noteToCourier: string | null;
            };
            driver: {
                id: string;
                city: import(".prisma/client").$Enums.City;
                createdAt: Date;
                updatedAt: Date;
                userId: string;
                driverType: import(".prisma/client").$Enums.DriverType;
                kycStatus: import(".prisma/client").$Enums.KycStatus;
                availability: import(".prisma/client").$Enums.Availability;
                isBusy: boolean;
                approvedAt: Date | null;
                rejectedAt: Date | null;
                kycNote: string | null;
            };
        } & {
            id: string;
            serviceType: import(".prisma/client").$Enums.ServiceType;
            city: import(".prisma/client").$Enums.City;
            status: import(".prisma/client").$Enums.TripStatus;
            cancelledBy: import(".prisma/client").$Enums.CancelledBy | null;
            cancelReason: string | null;
            pickupAddress: string;
            pickupLat: number;
            pickupLng: number;
            dropoffAddress: string;
            dropoffLat: number;
            dropoffLng: number;
            distanceKmEst: number | null;
            durationMinEst: number | null;
            requestedAt: Date;
            matchedAt: Date | null;
            acceptedAt: Date | null;
            arrivedAt: Date | null;
            startedAt: Date | null;
            completedAt: Date | null;
            cancelledAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            paymentMode: import(".prisma/client").$Enums.PaymentMode;
            commitmentStatus: import(".prisma/client").$Enums.CommitmentStatus;
            commitmentAmount: number | null;
            commitmentWaivedAt: Date | null;
            commitmentWaivedBy: string | null;
            commitmentReason: string | null;
            riderId: string;
            driverId: string | null;
        })[];
        message?: undefined;
    } | {
        ok: boolean;
        message: string;
        trips?: undefined;
    }>;
    private expireStaleRequestedTrips;
    inbox(user: any): Promise<{
        ok: boolean;
        message: string;
        phase4Marker?: undefined;
        expiredCount?: undefined;
        count?: undefined;
        windowMinutes?: undefined;
        driver?: undefined;
        trips?: undefined;
    } | {
        ok: boolean;
        phase4Marker: string;
        expiredCount: number;
        count: number;
        windowMinutes: number;
        driver: {
            id: string;
            userId: string;
            driverType: import(".prisma/client").$Enums.DriverType;
            city: "ABUJA";
            availability: "ONLINE";
            lat: number;
            lng: number;
            lastSeenAt: Date;
        };
        trips: {
            distanceKm: number;
            delivery: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                tripId: string;
                itemDescription: string;
                recipientName: string;
                recipientPhone: string;
                noteToCourier: string | null;
            };
            rider: {
                id: string;
                status: import(".prisma/client").$Enums.UserStatus;
                createdAt: Date;
                updatedAt: Date;
                phone: string;
                role: import(".prisma/client").$Enums.Role;
                fullName: string | null;
                email: string | null;
                isMerchant: boolean;
                merchantTrusted: boolean;
            };
            id: string;
            serviceType: import(".prisma/client").$Enums.ServiceType;
            city: import(".prisma/client").$Enums.City;
            status: import(".prisma/client").$Enums.TripStatus;
            cancelledBy: import(".prisma/client").$Enums.CancelledBy | null;
            cancelReason: string | null;
            pickupAddress: string;
            pickupLat: number;
            pickupLng: number;
            dropoffAddress: string;
            dropoffLat: number;
            dropoffLng: number;
            distanceKmEst: number | null;
            durationMinEst: number | null;
            requestedAt: Date;
            matchedAt: Date | null;
            acceptedAt: Date | null;
            arrivedAt: Date | null;
            startedAt: Date | null;
            completedAt: Date | null;
            cancelledAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            paymentMode: import(".prisma/client").$Enums.PaymentMode;
            commitmentStatus: import(".prisma/client").$Enums.CommitmentStatus;
            commitmentAmount: number | null;
            commitmentWaivedAt: Date | null;
            commitmentWaivedBy: string | null;
            commitmentReason: string | null;
            riderId: string;
            driverId: string | null;
        }[];
        message?: undefined;
    }>;
    cancel(user: any, tripId: string, body?: {
        reason?: string;
    }): Promise<{
        ok: true;
        trip: {
            fare: {
                createdAt: Date;
                tripId: string;
                currency: import(".prisma/client").$Enums.Currency;
                baseFare: number;
                perKmFare: number;
                perMinFare: number;
                bookingFee: number;
                discount: number;
                totalAmount: number;
                platformEarning: number;
                driverEarning: number;
                distanceKm: number | null;
                durationMin: number | null;
            };
            delivery: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                tripId: string;
                itemDescription: string;
                recipientName: string;
                recipientPhone: string;
                noteToCourier: string | null;
            };
            driver: {
                id: string;
                city: import(".prisma/client").$Enums.City;
                createdAt: Date;
                updatedAt: Date;
                userId: string;
                driverType: import(".prisma/client").$Enums.DriverType;
                kycStatus: import(".prisma/client").$Enums.KycStatus;
                availability: import(".prisma/client").$Enums.Availability;
                isBusy: boolean;
                approvedAt: Date | null;
                rejectedAt: Date | null;
                kycNote: string | null;
            };
            rider: {
                id: string;
                status: import(".prisma/client").$Enums.UserStatus;
                createdAt: Date;
                updatedAt: Date;
                phone: string;
                role: import(".prisma/client").$Enums.Role;
                fullName: string | null;
                email: string | null;
                isMerchant: boolean;
                merchantTrusted: boolean;
            };
        } & {
            id: string;
            serviceType: import(".prisma/client").$Enums.ServiceType;
            city: import(".prisma/client").$Enums.City;
            status: import(".prisma/client").$Enums.TripStatus;
            cancelledBy: import(".prisma/client").$Enums.CancelledBy | null;
            cancelReason: string | null;
            pickupAddress: string;
            pickupLat: number;
            pickupLng: number;
            dropoffAddress: string;
            dropoffLat: number;
            dropoffLng: number;
            distanceKmEst: number | null;
            durationMinEst: number | null;
            requestedAt: Date;
            matchedAt: Date | null;
            acceptedAt: Date | null;
            arrivedAt: Date | null;
            startedAt: Date | null;
            completedAt: Date | null;
            cancelledAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            paymentMode: import(".prisma/client").$Enums.PaymentMode;
            commitmentStatus: import(".prisma/client").$Enums.CommitmentStatus;
            commitmentAmount: number | null;
            commitmentWaivedAt: Date | null;
            commitmentWaivedBy: string | null;
            commitmentReason: string | null;
            riderId: string;
            driverId: string | null;
        };
        message?: undefined;
    } | {
        ok: boolean;
        message: string;
    }>;
    accept(user: any, tripId: string): Promise<{
        ok: true;
        trip: {
            delivery: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                tripId: string;
                itemDescription: string;
                recipientName: string;
                recipientPhone: string;
                noteToCourier: string | null;
            };
            driver: {
                id: string;
                city: import(".prisma/client").$Enums.City;
                createdAt: Date;
                updatedAt: Date;
                userId: string;
                driverType: import(".prisma/client").$Enums.DriverType;
                kycStatus: import(".prisma/client").$Enums.KycStatus;
                availability: import(".prisma/client").$Enums.Availability;
                isBusy: boolean;
                approvedAt: Date | null;
                rejectedAt: Date | null;
                kycNote: string | null;
            };
            rider: {
                id: string;
                status: import(".prisma/client").$Enums.UserStatus;
                createdAt: Date;
                updatedAt: Date;
                phone: string;
                role: import(".prisma/client").$Enums.Role;
                fullName: string | null;
                email: string | null;
                isMerchant: boolean;
                merchantTrusted: boolean;
            };
        } & {
            id: string;
            serviceType: import(".prisma/client").$Enums.ServiceType;
            city: import(".prisma/client").$Enums.City;
            status: import(".prisma/client").$Enums.TripStatus;
            cancelledBy: import(".prisma/client").$Enums.CancelledBy | null;
            cancelReason: string | null;
            pickupAddress: string;
            pickupLat: number;
            pickupLng: number;
            dropoffAddress: string;
            dropoffLat: number;
            dropoffLng: number;
            distanceKmEst: number | null;
            durationMinEst: number | null;
            requestedAt: Date;
            matchedAt: Date | null;
            acceptedAt: Date | null;
            arrivedAt: Date | null;
            startedAt: Date | null;
            completedAt: Date | null;
            cancelledAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            paymentMode: import(".prisma/client").$Enums.PaymentMode;
            commitmentStatus: import(".prisma/client").$Enums.CommitmentStatus;
            commitmentAmount: number | null;
            commitmentWaivedAt: Date | null;
            commitmentWaivedBy: string | null;
            commitmentReason: string | null;
            riderId: string;
            driverId: string | null;
        };
        message?: undefined;
    } | {
        ok: boolean;
        message: string;
    }>;
    start(user: any, tripId: string): Promise<{
        ok: boolean;
        message: string;
        trip?: undefined;
    } | {
        ok: boolean;
        trip: {
            delivery: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                tripId: string;
                itemDescription: string;
                recipientName: string;
                recipientPhone: string;
                noteToCourier: string | null;
            };
        } & {
            id: string;
            serviceType: import(".prisma/client").$Enums.ServiceType;
            city: import(".prisma/client").$Enums.City;
            status: import(".prisma/client").$Enums.TripStatus;
            cancelledBy: import(".prisma/client").$Enums.CancelledBy | null;
            cancelReason: string | null;
            pickupAddress: string;
            pickupLat: number;
            pickupLng: number;
            dropoffAddress: string;
            dropoffLat: number;
            dropoffLng: number;
            distanceKmEst: number | null;
            durationMinEst: number | null;
            requestedAt: Date;
            matchedAt: Date | null;
            acceptedAt: Date | null;
            arrivedAt: Date | null;
            startedAt: Date | null;
            completedAt: Date | null;
            cancelledAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            paymentMode: import(".prisma/client").$Enums.PaymentMode;
            commitmentStatus: import(".prisma/client").$Enums.CommitmentStatus;
            commitmentAmount: number | null;
            commitmentWaivedAt: Date | null;
            commitmentWaivedBy: string | null;
            commitmentReason: string | null;
            riderId: string;
            driverId: string | null;
        };
        message?: undefined;
    }>;
    complete(user: any, tripId: string, body?: {
        distanceKmEst?: number;
        durationMinEst?: number;
    }): Promise<{
        ok: boolean;
        message: string;
        trip?: undefined;
        fare?: undefined;
        walletUpdated?: undefined;
        alreadyCompleted?: undefined;
    } | {
        ok: boolean;
        trip: {
            id: string;
            serviceType: import(".prisma/client").$Enums.ServiceType;
            city: import(".prisma/client").$Enums.City;
            status: import(".prisma/client").$Enums.TripStatus;
            cancelledBy: import(".prisma/client").$Enums.CancelledBy | null;
            cancelReason: string | null;
            pickupAddress: string;
            pickupLat: number;
            pickupLng: number;
            dropoffAddress: string;
            dropoffLat: number;
            dropoffLng: number;
            distanceKmEst: number | null;
            durationMinEst: number | null;
            requestedAt: Date;
            matchedAt: Date | null;
            acceptedAt: Date | null;
            arrivedAt: Date | null;
            startedAt: Date | null;
            completedAt: Date | null;
            cancelledAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            paymentMode: import(".prisma/client").$Enums.PaymentMode;
            commitmentStatus: import(".prisma/client").$Enums.CommitmentStatus;
            commitmentAmount: number | null;
            commitmentWaivedAt: Date | null;
            commitmentWaivedBy: string | null;
            commitmentReason: string | null;
            riderId: string;
            driverId: string | null;
        };
        fare: {
            createdAt: Date;
            tripId: string;
            currency: import(".prisma/client").$Enums.Currency;
            baseFare: number;
            perKmFare: number;
            perMinFare: number;
            bookingFee: number;
            discount: number;
            totalAmount: number;
            platformEarning: number;
            driverEarning: number;
            distanceKm: number | null;
            durationMin: number | null;
        };
        walletUpdated: boolean;
        alreadyCompleted: boolean;
        message?: undefined;
    }>;
}
